### ISSUE TITLE
Echodoc does not show function signatures

### ISSUE THREAD

**Issue by landge** [Shougo/echodoc.vim#54] opened 2018-11-06 10:32 UTC
Hi,

I'm having problems getting echodoc to work with my setup.
Can anyone spot an obvious configuration issue?

Here's my neovim checkhealth:

`health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#jedi#check
========================================================================
##### jedi-vim version

 - jedi-vim git version: b6dfc5f
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  930ec08ab0cd77aae07e24aa78f9c5119be216bb pythonx/parso (v0.3.1-7-g930ec08)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09), [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]`
 - global site module: `/Users/landge/miniconda3/lib/python3.6/site.py`

##### Jedi

 - path: `/Users/landge/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.6.5 in /Users/landge/miniconda3>

 - executable: /Users/landge/miniconda3/bin/python3
 - sys_path:
    - `/Users/landge/miniconda3/lib/python36.zip`
    - `/Users/landge/miniconda3/lib/python3.6`
    - `/Users/landge/miniconda3/lib/python3.6/lib-dynload`
    - `/Users/landge/miniconda3/lib/python3.6/site-packages`
    - `/Users/landge/miniconda3/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg`

##### Known environments

 - <Environment: 3.6.5 in /Users/landge/miniconda3> (/Users/landge/miniconda3/bin/python3.6)

 - <Environment: 2.7.14 in /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7> (/usr/local/opt/python@2/bin/python2.7)

##### Settings

```
g:jedi#show_call_singatures = '1' (default: '-')


  omnifunc=htmlcomplete#CompleteTags
	Last set from /usr/local/Cellar/neovim/0.3.1/share/nvim/runtime/ftplugin/html.vim
  completeopt=menuone,longest,preview
	Last set from ~/.local/share/nvim/plugged/jedi-vim/plugin/jedi.vim
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/local/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /Users/landge/miniconda3/bin/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /Users/landge/miniconda3/bin/python3
  - INFO: Other python executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.5
  - INFO: python3-neovim version: 0.3.0
  - OK: Latest python3-neovim is installed: 0.3.0

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.2.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

`

And my init.vim:

call plug#begin('~/.local/share/nvim/plugged')
Plug 'vim-python/python-syntax'
Plug 'rafi/awesome-vim-colorschemes'
Plug 'scrooloose/nerdtree'
if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
endif
Plug 'vim-airline/vim-airline'
Plug 'Shougo/echodoc.vim'
Plug 'zchee/deoplete-jedi'
Plug 'davidhalter/jedi-vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'rakr/vim-one'
call plug#end()
set termguicolors
let  g:deoplete#sources#jedi#show_docstring=0
let  g:echodoc_enable_at_startup="1"
let  g:airline_theme='one'
let  g:echodoc_type='echo'
let  g:jedi#show_call_singatures= "1"
colorscheme  one
set background=dark
set cmdheight=2
call deoplete#enable()

The completions are shown in a pop-up, but the signatures are not shown.

<img width="480" alt="screenshot 2018-11-06 at 11 28 44" src="https://user-images.githubusercontent.com/25629/48058638-3046a100-e1b7-11e8-9bee-58bc99d4fcf4.png">

<img width="530" alt="screenshot 2018-11-06 at 11 30 43" src="https://user-images.githubusercontent.com/25629/48058721-70a61f00-e1b7-11e8-9aa6-c3003296a6e6.png">

Nothing is shown after selecting the candidate with Ctrl-n, Ctrl-y

Thanks in advance,
landge

**Comment by Shougo** [comment] 2018-11-07 02:45
I have tested it and it is expected behavior.
pandas.DataFrame is module and it doesn't have function prototype.
echodoc works for function prototype only.
Closing.

**Closed** 2018-11-07 02:45 UTC

**Comment by Shougo** [comment] 2018-11-07 02:46
You can test os.access instead.  It works for me.

**Comment by landge** [comment] 2018-11-07 10:21
Great, thank you!
