### ISSUE TITLE
Don't open bracket.

### ISSUE THREAD

**Issue by karambaq** [Shougo/echodoc.vim#35] opened 2017-12-01 16:26 UTC
Hello, don't is it deoplete issue or echodoc, so I just leave a link on gif.

Gif : https://imgur.com/a/SsNSW
```vim
if has('nvim')
   Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
   Plug 'Shougo/deoplete.nvim'
   Plug 'roxma/nvim-yarp'
   Plug 'roxma/vim-hug-neovim-rpc'
endif

Plug 'zchee/deoplete-jedi'
Plug 'Shougo/echodoc.vim'

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 500
let g:deoplete#sources#jedi#show_call_signatures = 1
let g:echodoc#enable_at_startup = 1
let g:deoplete#sources#jedi#show_docstring = 1
set cmdheight=2
```

As you can see on gif, It don't open the bracket '(' when I choose variant and tap enter, so and docstring works only 1 of 4 times.

Thank you.

**Comment by Shougo** [comment] 2017-12-03 03:54
I will test the problem.
Please upload the example script.

And the reproduce ways from Vim starting is needed.

And, you have uploaded the screenshot without the minimal vimrc.
Because, you have not include the statusline plugin in the minimal vimrc.
Please upload the screenshot using the minimal vimrc.

**Comment by Shougo** [comment] 2017-12-03 03:57
Note: I will close the issue if you don't upload the reproduce ways.

**Comment by Shougo** [comment] 2017-12-06 02:09
@karambaq I have tested it, but I cannot reproduced.
So please upload the Python script and the reproduce ways by text.

For example:
https://github.com/Shougo/deoplete.nvim/issues/585

If not, unfortunately I will close the issue.
I have not much time to not reproduceable problem.
It works for me.

Related problem?
https://github.com/Shougo/echodoc.vim/issues/33

**Comment by karambaq** [comment] 2017-12-06 10:54
@Shougo  Oh, I think I got you.

So, here is screenshot (some error on the bottom).
![image](https://user-images.githubusercontent.com/14233969/33658119-9b659730-da8c-11e7-8417-f444a6c3f69a.png)

My init.vim
`call plug#begin('~/.local/share/nvim/plugged')
if has('nvim')
	Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else 
	Plug 'Shougo/deoplete.nvim'
	Plug 'roxma/nvim-yarp'
	Plug 'roxma/vim-hug-neovim-rpc'
endif

Plug 'zchee/deoplete-jedi'
Plug 'Shougo/echodoc.vim'

call plug#end()

let g:deoplete#enable_at_startup = 1
let g:echodoc#enable_at_sartup = 1
set cmdheight=2
`

And python script

`import requests

a = requests.

`

So I see some docstring on the top, but it's not a echodoc I think, because I tried to remove echodoc plug and It still working.

**Comment by Shougo** [comment] 2017-12-06 12:57
@karambaq 

It is just preview window feature.
Please disable the preview window.

> So I see some docstring on the top, but it's not a echodoc I think, because I tried to remove echodoc plug and It still working.

```vim
set completeopt-=preview
```

**Comment by karambaq** [comment] 2017-12-06 13:06
I disable it:
Gif: https://imgur.com/a/Me6Zz

**Comment by Shougo** [comment] 2017-12-07 02:01
OK.  One question:

Why don't you use the minimal vimrc?
In the above gif, it installs statusline plugin(airline?).
It is not included in minimal vimrc.

I will close the issue sorry.

**Closed by Shougo** 2017-12-07 02:01 UTC
Labels: reproduce ways

**Comment by Shougo** [comment] 2017-12-07 02:04
OK.  I get the reason.

```vim
let g:echodoc#enable_at_sartup = 1
```

It is the wrong name.

It must be `let g:echodoc#enable_at_startup = 1`.
So echodoc is disabled in your vimrc.

**Comment by Shougo** [comment] 2017-12-07 02:05
Please check echodoc is working.
You can enable echodoc by `EchoDocEnable`.

**Comment by karambaq** [comment] 2017-12-07 16:25
@Shougo Because this plugins installed via aur.
Yeah, you right, typo, I change it, seems works now.

**Comment by Shougo** [comment] 2017-12-08 01:33
OK.
