### ISSUE TITLE
How to enable echodoc for PHP?

### ISSUE THREAD

**Issue by marlun** [Shougo/echodoc.vim#10] opened 2015-08-18 12:56 UTC
I've read issues for both echodoc and neocomplete but I can't seem to understand how to enable echodoc. I've got noshowmode, neocomplete and echodoc installed and both set to be enabled. Do I need to add something more? When the completion popup is shown and if I choose a function and hit C-y, nothing is shown.

**Comment by 7belrhalmia** [comment] 2015-08-18 13:02
@marlun  you sould only update to the last vim patch download vim and compilit with lua and python support and it will work inshallah

**Comment by 7belrhalmia** [comment] 2015-08-18 13:03
@marlun  and also use eclim tocomplete php to get full completion if you use php oriented object

**Comment by marlun** [comment] 2015-08-18 13:34
@7belrhalmia I'm sorry but I'm having a hard time understanding what you're writing. I've already got vim 7.4.803 installed with lua and python support, neocomplete works fine.

**Comment by 7belrhalmia** [comment] 2015-08-18 13:43
ok @marlun you can't complete php code only with neocomplete  you have to use eclim

**Comment by 7belrhalmia** [comment] 2015-08-18 13:45
and do in your vimrc 
    set cmdheight=2
    let g:echodoc_enable_at_startup

**Comment by marlun** [comment] 2015-08-18 14:11
How come phpcomplete.vim and neocomplete isn't enough? Really wouldn't want to install even more things.

As far as I've read cmdheight=2 isn't needed if you've got 'noshowmode'?

**Comment by 7belrhalmia** [comment] 2015-08-18 16:30
nn you must do cmdheight test it and tell me

**Comment by marlun** [comment] 2015-08-18 20:59
Just adding cmdheight=2 didn't work either and I really don't want to install eclim. If that's a requirement I'll have to pass on echodoc unfortunately.

**Comment by Shougo** [comment] 2015-08-20 12:21
@marlun I have not PHP environment.
Please create minimal .vimrc and reproduce ways from Vim starting.

**Comment by Shougo** [comment] 2015-08-20 12:23
And you must enable echodoc.

```vim
  let g:echodoc_enable_at_startup = 1
```

**Comment by marlun** [comment] 2015-09-20 17:42
I just added the following

    if !exists('g:neocomplete#sources#omni#input_patterns')
	    let g:neocomplete#sources#omni#input_patterns = {}
    endif
    let g:neocomplete#sources#omni#input_patterns.php =
			\ '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

and now echodoc is displaying the params in the command line.

**Comment by Shougo** [comment] 2015-09-23 01:35
OK.  The problem is gone.  Closing.

**Closed by Shougo** 2015-09-23 01:35 UTC
